### ISSUE TITLE
silent 这个字段好像没作用吧

### ISSUE THREAD

**Issue by qingtian0622** [leanflutter/screen_capturer#1]
await ScreenCapturer.instance.capture(
          imagePath: "C:\\hxs\\product\\hxs_${DateFormat("yyyyMMddHHmmss").format(DateTime.now())}.jpg",
          silent: true
        )

silent不管是true还是false，都没法静默截图

**Comment by lijy91** [comment]
silent 参数仅在 macOS 下有效，作用是关闭截图成功音效
