### ISSUE TITLE
[macOS] isAccessAllowed always false

### ISSUE THREAD

**Issue by manarhidayat** [leanflutter/screen_capturer#13]
i already add my app to allow screen recording in Privacy & Policy
but status isAccessAllowed always false

OS: macOS Ventura 13.0.1

**Comment by sunjianan9900** [comment]
hey ，how did you solve the problem?

**Comment by linguowei** [comment]
I have the same problem

OS: macOS Ventura 13.2.1

**Comment by manarhidayat** [comment]
@sunjianan9900 @linguowei i created to check the permission myself on native
