### ISSUE TITLE
Capture multiple screens

### ISSUE THREAD

**Issue by tbsmanish** [leanflutter/screen_capturer#14]
I should be capable of capturing multi screens if attached. @lijy91

**Comment by lijy91** [comment]
This plug-in can only call system screenshots, which may not support this capability.

**Comment by tbsmanish** [comment]
I HAVE BEEN THROUGH THIS BUT AS YOU CAN CHECK WHEN CAPTURING SS ON WINDOWS IT CAPTURES ALL CONNECTED WINDOW YOU CAN TRY IT BY WINDOW + PRINTSCREEN

**Comment by tbsmanish** [comment]
can I create pr for this I got the solution. @lijy91

**Comment by lijy91** [comment]
Of course, looking forward to your contribution.

**Comment by muhsinzyne** [comment]
> can I create pr for this I got the solution. @lijy91

could you please provide me this ???

**Comment by muhsinzyne** [comment]
any updates ???
