### ISSUE TITLE
Exception: Build process failed.

### ISSUE THREAD

**Issue by dHanel** [leanflutter/screen_capturer#25]
I get the following error if i add screen_capturer: ^0.1.7 and try to build:

```
Launching lib\main.dart on Windows in debug mode...
Exception: Build process failed.

Exited (1).
```

Im on Windows11 and tried to build for windows desktop. I do not have anything else in my project. Just the sample project and as soon as i add screen_capturer dependency to my pubspec.yaml i get this error when building.

Does anyone else have this problem aswell?

**Comment by lijy91** [comment]
Please try running example or clean project
