### ISSUE TITLE
Linux support problem

### ISSUE THREAD

**Issue by gvenusleo** [leanflutter/screen_capturer#26]
I noticed that `screen_capturer` takes screenshots by executing the `gnome-screenshot` command on the Linux platform, but in some distributions, `gnome-screenshot` is not the default screenshot software. For example, the default screenshot software in the KDE Plasma desktop environment is `spectacle` .

Are there plans to support more screenshot methods?

**Comment by Christian-Klempau** [comment]
Up! I have the same problem.
Is there a package independant linux screenshot tool packaged with flutter maybe?

**Comment by lijy91** [comment]
Please update to 0.2.0
