### ISSUE TITLE
不能正常使用，望大佬及时改进

### ISSUE THREAD

**Issue by lyingjack** [leanflutter/screen_capturer#34]
在macos上，区域截图和全屏截图都只能截取到桌面背景，window模式下报could not create image from window错误
在windows上，会启动第三方截屏工具，然后调用立即结束，第三方截图工具截到图片后没有通知回调，无法及时获取截图内容
希望大佬及时改进到能正常使用，万分感谢

**Comment by lijy91** [comment]
1. 是因为未开启相应的权限引起 `isAccessAllowed` 和 `requestAccess` 来判断是否有截图权限
2. windows 由于微信升级了截图软件引起，近期会修复。

**Comment by lijy91** [comment]
已修复，更新到 0.2.2 版本即可

**Comment by lyingjack** [comment]
windows端还是不能获取到截图数据，不知道是我哪里没操作对？前几天突然可以获取截图数据，但每次截图前要调用两次才能拉起截图工具，后来退出app重新编译后又不行了，今天更新到最新版还是获取不到截图数据，并且还会报无法打开剪贴板的错误，系统是windows 11

**Comment by lijy91** [comment]
看看电脑里的截图工具的版本是多少

**Comment by lyingjack** [comment]
感谢你的回复，我windows上有两个截图工具，我把默认截图工具换成另一个后截图正常了，只是第一次调用的时候还是会出现剪切板打开失败的现象，再点一次就好了
