### ISSUE TITLE
Deepin OS 支持以下不 

### ISSUE THREAD

**Issue by xiyionxiong** [leanflutter/screen_capturer#37]
Deepin OS 支持以下不

**Comment by lijy91** [comment]
本人不使用 DeepinOS，可以参考一下 spectacle 和 gnone_screenshot 的实现方式实现，欢迎 PR。

相关代码：
https://github.com/leanflutter/screen_capturer/blob/main/packages/screen_capturer_linux/lib/src/screen_capturer_linux.dart
https://github.com/leanflutter/screen_capturer/blob/main/packages/screen_capturer_linux/lib/src/commands/spectacle.dart
https://github.com/leanflutter/screen_capturer/blob/main/packages/screen_capturer_linux/lib/src/commands/gnome_screenshot.dart

**Comment by lijy91** [comment]
感谢您的 PR https://github.com/leanflutter/screen_capturer/pull/39 ，现已合入，请更新到 v0.2.3
