### ISSUE TITLE
store in variable without saving to disk

### ISSUE THREAD

**Issue by ashwin31** [leanflutter/screen_capturer#5]
Is it possible to store in variable without saving to disk?

like the following?
```
import 'package:screen_capturer/screen_capturer.dart';

CapturedData? capturedData = await screenCapturer.capture(
  mode: CaptureMode.screen
);
```

**Comment by ashwin31** [comment]
Hi @lijy91 can you guide me how to do this?

**Comment by lijy91** [comment]
All three platforms support saving to the clipboard after taking a screenshot. In theory, you only need to read the picture from the clipboard after the screenshot is successful.

**Comment by ashwin31** [comment]
Thank you but the path is mandatory in the capture function. so, the file is being saved in the imagePath. Can you please make the imagePath parameter as optional.

**Comment by Norman-w** [comment]
> Is it possible to store in variable without saving to disk?
> 
> like the following?
> 
> ```
> import 'package:screen_capturer/screen_capturer.dart';
> 
> CapturedData? capturedData = await screenCapturer.capture(
>   mode: CaptureMode.screen
> );
> ```

Please review:
[This PR](https://github.com/leanflutter/screen_capturer/pull/18)

**Comment by mathewthe2** [comment]
> > Is it possible to store in variable without saving to disk?
> > like the following?
> > ```
> > import 'package:screen_capturer/screen_capturer.dart';
> > 
> > CapturedData? capturedData = await screenCapturer.capture(
> >   mode: CaptureMode.screen
> > );
> > ```
> 
> Please review: [This PR](https://github.com/leanflutter/screen_capturer/pull/18)

The modified code does not support Mac or Linux. Please consider retaining compatibility with existing code on current platforms.

**Comment by lijy91** [comment]
It will be supported in the next version, examples are as follows:

```dart
await screenCapturer.capture(
  mode: CaptureMode.region,
  copyToClipboard: true,
);
```

**Comment by mathewthe2** [comment]
Is there a way to just capture the image data without using the clipboard?

**Comment by lijy91** [comment]
Please update to 0.1.5

**Comment by lijy91** [comment]
> Is there a way to just capture the image data without using the clipboard?

The clipboard must be used now, but the image data can be obtained through CapturedData.imageBytes.

**Comment by mathewthe2** [comment]
Can you at least share the issues that are preventing such an implementation? I've worked with screen capture libraries on Mac before without having to go through the clipboard or the file system, so if it's a Mac issue I could contribute.
