### ISSUE TITLE
Silent 'True' is not working

### ISSUE THREAD

**Issue by VivekTpss** [leanflutter/screen_capturer#6]
I have implemented this screen capture library. 
But it is giving me this photo capture animation. 

this is my code.

```
    await ScreenCapturer.instance.capture(
                    mode: CaptureMode.screen, // screen, window
                    imagePath: _finalDirectory + "/" +imageName,
                    silent: true,
                  );
```

**Comment by lijy91** [comment]
What platform? slient only works on macOS

**Comment by VivekTpss** [comment]
I am trying this on Linux. 
Is there any way through which we can implement the screenshot without showing the capture animation?

**Comment by lijy91** [comment]
The essence of screen_capturer is to call gnome-screenshot to realize the screenshot function, but gnome-screenshot does not support the function you want.
