### ISSUE TITLE
Add ATL dependencies setup steps for windows

### ISSUE THREAD

**Issue by Far-Se** [leanflutter/screen_capturer#8]
It's for people that do not have full Visual Studio Professional installed and have the basic tools flutter installed. Took me ~15 min to find the issue.
Open Visual Studio Installer, press on Modify for VS 2019, go to Individual components, search for ATL and install last version for your processor architecture.

**Comment by raj457036** [comment]
i am using vs community edition 2019 installed all ATL for (ARM and X86/X64) still its showing atlimage.not found

please help!
